#!/usr/bin/env python3
"""Verify and select literature candidates without fabricating references."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path


def parse_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def normalize_title(text: str) -> str:
    return re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "", text.lower())


def parse_target(raw: str, fallback: int) -> int:
    match = re.match(r"(\d+)", str(raw).strip())
    return int(match.group(1)) if match else fallback


def within_year(year: str, start: int, end: int) -> bool:
    if not year.isdigit():
        return False
    value = int(year)
    return start <= value <= end


def locatable(row: dict[str, str]) -> bool:
    return any(row.get(key, "").strip() for key in ("doi", "landing_page", "pdf_url", "local_file"))


def select_rows(rows: list[dict[str, str]], start: int, end: int, zh_target: int, en_target: int) -> tuple[list[dict[str, str]], list[str]]:
    seen: set[str] = set()
    selected: list[dict[str, str]] = []
    shortages: list[str] = []

    ranked = sorted(
        rows,
        key=lambda row: (
            row.get("download_status") == "downloaded",
            bool(row.get("doi")),
            bool(row.get("local_file")),
            bool(row.get("landing_page")),
            row.get("year", ""),
        ),
        reverse=True,
    )

    zh_count = 0
    en_count = 0
    for row in ranked:
        title = row.get("title", "").strip()
        if not title or not locatable(row) or not within_year(row.get("year", ""), start, end):
            continue
        key = normalize_title(title) + "_" + row.get("year", "")
        if key in seen:
            continue
        language = row.get("language", "").strip().lower()
        if language == "zh" and zh_count >= zh_target:
            continue
        if language != "zh" and en_count >= en_target:
            continue
        seen.add(key)
        selected.append(row)
        if language == "zh":
            zh_count += 1
        else:
            en_count += 1
        if zh_count >= zh_target and en_count >= en_target:
            break

    if zh_count < zh_target:
        shortages.append(f"Chinese literature shortage: expected at least {zh_target}, found {zh_count}.")
    if en_count < en_target:
        shortages.append(f"English literature shortage: expected at least {en_target}, found {en_count}.")
    return selected, shortages


def write_selected_csv(path: Path, rows: list[dict[str, str]]) -> None:
    fieldnames = [
        "title",
        "authors",
        "year",
        "language",
        "venue",
        "doi",
        "landing_page",
        "pdf_url",
        "download_status",
        "local_file",
        "source",
        "query",
    ]
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_report(path: Path, rows: list[dict[str, str]], shortages: list[str], start: int, end: int) -> None:
    zh_count = sum(1 for row in rows if row.get("language") == "zh")
    en_count = len(rows) - zh_count
    lines = [
        "# Verified Literature Selection",
        "",
        f"- Selected rows: `{len(rows)}`",
        f"- Chinese rows: `{zh_count}`",
        f"- English/other rows: `{en_count}`",
        f"- Year range enforced: `{start}-{end}`",
        "",
        "## Selected Items",
        "",
    ]
    for idx, row in enumerate(rows, 1):
        locator = row.get("doi") or row.get("local_file") or row.get("landing_page") or row.get("pdf_url") or "missing"
        lines.append(f"{idx}. {row.get('title', '')} ({row.get('year', '')}) [{row.get('language', '')}]")
        lines.append(f"   - Locator: `{locator}`")
    if shortages:
        lines.extend(["", "## Shortages", ""])
        lines.extend(f"- {item}" for item in shortages)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify and select literature candidates.")
    parser.add_argument("candidate_csv", help="Candidate CSV generated by run_keyword_harvest_no_dedup.py")
    parser.add_argument("--config", help="literature-harvest-config.json for year range and target counts.")
    parser.add_argument("--out", default="paper-context/literature/verified-selection", help="Output directory.")
    args = parser.parse_args()

    candidate_path = Path(args.candidate_csv).resolve()
    config = {}
    if args.config:
        config = json.loads(Path(args.config).resolve().read_text(encoding="utf-8"))
    policy = config.get("policy", {})
    start = int(policy.get("year_start", 2021))
    end = int(policy.get("year_end", 2026))
    target_counts = policy.get("target_counts", {})
    zh_target = parse_target(target_counts.get("zh", "12-15"), 12)
    en_target = parse_target(target_counts.get("en", "3-5"), 3)

    rows = parse_rows(candidate_path)
    selected, shortages = select_rows(rows, start, end, zh_target, en_target)

    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / "verified-literature-selected.csv"
    md_path = out_dir / "verified-literature-selection.md"
    write_selected_csv(csv_path, selected)
    write_report(md_path, selected, shortages, start, end)
    print(f"Wrote {csv_path}")
    print(f"Wrote {md_path}")
    return 0 if selected else 2


if __name__ == "__main__":
    raise SystemExit(main())
